main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('data_mhs/', views.data_mhs, name='data-mhs'),
    path('create/', views.create, name='create'),
    path('del_mhs/<del_id>', views.del_mhs, name='delete-mhs'),
    path('updt_mhs/<up_id>', views.updt_mhs, name='update-mhs'),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [

    path('', views.home, name='home'),
    path('vcenkripsi/', views.vcenkripsi, name='vcenkripsi'),
    path('vcdekripsi/', views.vcdekripsi, name='vcdekripsi'),
    path('caesarenc/', views.caesarenc, name='caesarenc'),
    path('caesardec/', views.caesardec, name='caesardec'),
    path('lsbembed/', views.lsbembed, name='lsbembed'),
    path('lsbextract/', views.lsbextract, name='lsbextract'),

]

seggaf181047/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls')),
    path('', include('main.urls')),
]

main/models.py
from django.db import models


class Mahasiswa(models.Model):
    nama = models.CharField(max_length=50)
    nim = models.CharField(max_length=20,primary_key=True)
    email = models.EmailField(max_length=100)

    def __str__(self):
        return self.nim

register/models.py
from django.db import models

main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .form import FormMhs
from .models import Mahasiswa


def home(request):
    context = {
        'judul' : 'Halaman Utama',
        'contributor': 'Yekk Seggaf',
    }
    return render(request, 'main/home.html', context)


def aboutme(request):
    return render(request, 'main/aboutme.html', {'judul' : 'Tentang Saya'})


def data_mhs(request):
    thedata = Mahasiswa.objects.all
    return render(request, 'main/data_mhs.html', {'data': thedata,
                                                  'judul': 'List Data Mahasiswa'})


def create(request):
    if request.method == 'POST':
        form = FormMhs(request.POST or None)
        if form.is_valid():
            form.save()
        else:
            nim = request.POST['nim']
            nama = request.POST['nama']
            email = request.POST['email']
            messages.success(request, ('Error!'))
            return render(request, 'main/create.html', {
                'nim': nim,
                'nama': nama,
                'email': email,
            })
        messages.success(request, ('Data telah berhasil dimasukkan.'))
        return redirect('/data_mhs')
    else:
        return render(request, 'main/create.html', {'judul': 'Input Data Mahasiswa'})


def del_mhs(request, del_id):
    mhsw = Mahasiswa.objects.get(pk=del_id)
    mhsw.delete()
    messages.success(request, ('Data telah dihapus.'))
    return redirect('/data_mhs')


def updt_mhs(request, up_id):
    mhsw = Mahasiswa.objects.get(pk=up_id)
    form = FormMhs(request.POST or None, instance=mhsw)
    if form.is_valid():
        form.save()
        return redirect('/data_mhs')
    return render(request, 'main/updt_mhs.html', {'mahasiswa': mhsw, 'form': form})

register/views.py
from django.shortcuts import render, redirect
from django.contrib import messages


def home(request):
    return render(request, 'home.html', {})


def vcenkripsi(request):
    if request.method == 'POST':
        plaintext = request.POST['plainteks']
        key = request.POST['kunci']
        key_length = len(key)
        key_as_int = [ord(i) for i in key]
        plaintext_int = [ord(i) for i in plaintext.upper()]
        ciphertext = ''
        for i in range(len(plaintext_int)):
            value = (plaintext_int[i] + key_as_int[i % key_length]) % 26
            ciphertext += chr(value + 65)
        context = {
            'plainteks': plaintext,
            'kunci': key,
            'dispcipher': ciphertext,
        }
        return render(request, 'vcenkripsi.html', context)
    else:
        return render(request, 'vcenkripsi.html', {})


def vcdekripsi(request):
    if request.method == 'POST':
        plaintext = request.POST['cipherteks']
        key = request.POST['kunci']
        key_length = len(key)
        key_as_int = [ord(i) for i in key]
        plaintext_int = [ord(i) for i in plaintext.upper()]
        ciphertext = ''
        for i in range(len(plaintext_int)):
            value = (plaintext_int[i] - key_as_int[i % key_length]) % 26
            ciphertext += chr(value + 65)
        context = {
            'cipherteks': plaintext,
            'kunci': key,
            'dispcipher': ciphertext,
        }
        return render(request, 'vcdekripsi.html', context)
    else:
        return render(request, 'vcdekripsi.html', {})


def caesarenc(request):
    if request.method == 'POST':
        plaintext = request.POST['plainteks']
        key = request.POST['kunci']
        ciphertext = ''
        for i in range(len(plaintext)):
            special = plaintext[i]
            new_special = special.lower()
            if new_special == " ":
                ciphertext = ciphertext + ' '
            elif special.isalpha():
                ciphertext = ciphertext + chr((ord(new_special) + int(key) - 97) % 26 + 97)
        context = {
            'plainteks': plaintext,
            'kunci': key,
            'dispcipher': ciphertext,
        }
        return render(request, 'caesarenc.html', context)
    else:
        return render(request, 'caesarenc.html', {})


def caesardec(request):
    if request.method == 'POST':
        ciphertext = request.POST['cipherteks']
        key = request.POST['kunci']
        plaintext = ''
        for i in range(len(ciphertext)):
            special = ciphertext[i]
            new_special = special.lower()
            if new_special == " ":
                plaintext += ' '
            elif special.isalpha():
                plaintext += chr((ord(new_special) - int(key) - 97) % 26 + 97)
        context = {
            'cipherteks': ciphertext,
            'kunci': key,
            'dispcipher': plaintext,
        }
        return render(request, 'caesardec.html', context)
    else:
        return render(request, 'caesardec.html', {})

def lsbembed(request):
    if request.method == 'POST':
        return render(request, 'lsbembed.html', {})
    else:
        return render(request, 'lsbembed.html', {})

def lsbextract(request):
    if request.method == 'POST':
        return render(request, 'lsbextract.html', {})
    else:
        return render(request, 'lsbextract.html', {})

main/templates/main/aboutme.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Belajar Django | {{judul}}</title>
{% endblock meta %}

{% block content %}
<h1 style="text-align:center">Biodataku</h1>
  <table style="margin-left: auto;  margin-right: auto;">
    <tr>
      <td style="width:160px"><img src="{% static 'img/profile.jpg' %}" width="150" height="225"></td>
      <td style="width:200px; vertical-align:top">
        Nama<br>
        NIM<br>
        Asal Universitas<br>
        Tempat Lahir<br>
        Tanggal Lahir<br>
        Agama<br>
        Kewarganegaraan<br>
        Status<br>
        Email<br>
        WA<br>
        Instagram<br>
      </td>
      <td style="width:10px; vertical-align:top">
        :<br>
        :<br>
        :<br>
        :<br>
        :<br>
        :<br>
        :<br>
        :<br>
        :<br>
        :<br>
        :<br>
      </td>
      <td style="width:200px; vertical-align:top">
        Muhammad Seggaf<br>
        181810101047<br>
        Universitas Jember<br>
        Situbondo<br>
        11 Juni 1999<br>
        Islam<br>
        Indonesia<br>
        Belum Menikah<br>
        181810101047@mail.unej.ac.id<br>
        085331729202<br>
        yekk_aidid11<br>
      </td>
    </tr>
  </table>
{% endblock content %}

main/templates/main/create.html
{% extends 'base.html' %}

{% block meta %}
<title>Belajar Django | {{judul}}</title>
{% endblock meta %}

{% block content %}
<h3>Input Data Mahasiswa</h3><br>
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <input type="text" class="form-control" name="nim" aria-describedby="emailHelp" value="{{nim}}"
               placeholder="NIM">
    </div>
    <div class="mb-3">
        <input type="text" class="form-control" name="nama" aria-describedby="emailHelp" value="{{nama}}"
               placeholder="Nama">
    </div>
    <div class="mb-3">
        <input type="email" class="form-control" name="email" aria-describedby="emailHelp" value="{{email}}"
               placeholder="Email : example@mail.com">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

main/templates/main/data_mhs.html
{% extends 'base.html' %}

{% block meta %}
<title>Belajar Django | {{judul}}</title>
{% endblock meta %}

{% block content %}
<h2 align="center">Data Mahasiswa</h2>
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
<button type="button" class="btn btn-success btn-sm" onclick="location.href='{% url 'main:create' %}'">+
    Tambah Data
</button></div>
<br>
<table class="table">
    <thead class="table-dark">
    <tr>
        <th scope="col" style="text-align:center">NIM</th>
        <th scope="col" style="text-align:center">Nama</th>
        <th scope="col" style="text-align:center">Email</th>
        <th scope="col" style="text-align:center">Aksi</th>
    </tr>
    </thead>
    <tbody>
    {% for isi in data %}
    <tr valign="middle">
        <td width="130px">{{isi.nim}}</td>
        <td>{{isi.nama}}</td>
        <td>{{isi.email}}</td>
        <td width="120px">
            <button type="button" class="btn btn-primary btn-sm"
                    onclick="location.href='{% url 'main:update-mhs' isi.nim %}'">
                Edit
            </button>
            <button type="button" class="btn btn-danger btn-sm"
                    onclick="location.href='{% url 'main:delete-mhs' isi.nim %}'">
                Hapus
            </button>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}

{% block meta %}
<title>Belajar Django | {{judul}}</title>
{% endblock meta %}

{% block content %}
<h2>Selamat Datang, Pengunjung!</h2>
<br>
<h3 style="font-weight:bold">What is Django?</h3>
Django is a high-level Python Web framework that encourages rapid development and clean pragmatic design. A Web framework is a set of components that provide a standard way to develop websites fast and easily. Django’s primary goal is to ease the creation of complex database-driven websites. Some well known sites that use Django include PBS, Instagram, Disqus, Washington Times, Bitbucket and Mozilla.
{% endblock content %}

main/templates/main/updt_mhs.html
{% extends 'base.html' %}

{% block meta %}
<title>Update Data</title>
{% endblock meta %}

{% block content %}
<h3>Update Data Mahasiswa</h3><br>
<div class="form-group">
    <form action="" method="POST">
        {% csrf_token%}
        {{ form.as_p }}
        <br>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
{% endblock content %}

register/templates/caesardec.html
{% extends 'register.html' %}

{% block meta %}
<title>Dekripsi Caesar Cipher</title>
{% endblock meta %}

{% block content %}
<h2 align="center">Dekripsi <i>Caesar Cipher</i></h2><br>
<div class="row justify-content-around">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <b>Proses </b>
            </div>
            <div class="card-body">
                <form method="post" name="enkripsi">
                    {% csrf_token %}
                    <div class="mb-3">
                        <textarea class="form-control" name="cipherteks" rows="7" placeholder="Cipherteks">{{cipherteks}}</textarea>
                    </div>
                    <div class="mb-3">
                        <textarea class="form-control" name="kunci" rows="7" placeholder="Kunci">{{kunci}}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Dekripsi</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-header">
                <b>Hasil Dekripsi</b>
            </div>
            <div class="card-body">
                <p class="card-text">{{dispcipher}}</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

register/templates/caesarenc.html
{% extends 'register.html' %}

{% block meta %}
<title>Enkripsi Caesar Cipher</title>
{% endblock meta %}

{% block content %}
<h2 align="center">Enkripsi <i>Caesar Cipher</i></h2><br>
<div class="row justify-content-around">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <b>Proses Enkripsi</b>
            </div>
            <div class="card-body">
                <form method="post" name="enkripsi">
                    {% csrf_token %}
                    <div class="mb-3">
                        <textarea class="form-control" name="plainteks" rows="7" placeholder="Plainteks">{{plainteks}}</textarea>
                    </div>
                    <div class="mb-3">
                        <textarea class="form-control" name="kunci" rows="7" placeholder="Kunci">{{kunci}}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Enkripsi</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-header">
                <b>Hasil Enkripsi</b>
            </div>
            <div class="card-body">
                <p class="card-text">{{dispcipher}}</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

register/templates/home.html
{% extends 'register.html' %}

{% block meta %}
<title>Cryptography APP</title>
{% endblock meta %}

{% block content %}
<h2 align="center">Kriptografi & Steganografi</i></h2><br>
<div class="row justify-content-around">
    <div class="col">
        <div class="list-group">
            <li class="list-group-item list-group-item-success"><i>Vigenere Cipher</i></li>
            <a href="{% url 'register:vcenkripsi' %}" class="list-group-item list-group-item-action">Enkripsi</a>
            <a href="{% url 'register:vcdekripsi' %}" class="list-group-item list-group-item-action">Dekripsi</a>
        </div>
        <div class="list-group">
            <li class="list-group-item list-group-item-primary"><i>Caesar Cipher</i></li>
            <a href="{% url 'register:caesarenc' %}" class="list-group-item list-group-item-action">Enkripsi</a>
            <a href="{% url 'register:caesardec' %}" class="list-group-item list-group-item-action">Dekripsi</a>
        </div>
    </div>
    <div class="col">
        <div class="list-group">
            <li class="list-group-item list-group-item-success"><i>Least Significant Bit</i></li>
            <a href="{% url 'register:lsbembed' %}" class="list-group-item list-group-item-action">Embed</a>
            <a href="{% url 'register:lsbextract' %}" class="list-group-item list-group-item-action">Extract</a>
        </div>
        <div class="list-group">
            <li class="list-group-item list-group-item-primary"><i>Histogram Shifting</i></li>
            <a href="#" class="list-group-item list-group-item-action">Embed</a>
            <a href="#" class="list-group-item list-group-item-action">Extract</a>
        </div>
    </div>
</div>

{% endblock content %}

register/templates/lsbembed.html
{% extends 'register.html' %}

{% block meta %}
<title>Enkripsi Vigenere Cipher</title>
{% endblock meta %}

{% block content %}
<h2 align="center">Enkripsi <i>Vigenere Cipher</i></h2><br>
<div class="row justify-content-around">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <b>Proses <i>Embed</i></b>
            </div>
            <div class="card-body">
                <form method="post" name="enkripsi">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="form-label">Pilih <i>cover image</i> </label>
                        <input class="form-control form-control-sm" name="coverimg" id="image-source" onchange="previewImage();" type="file" accept="image/png">
                        <br><center><img id="image-preview" alt="Image Preview" width="90%"/></center>
                    </div>
                    <div class="mb-3">
                        <textarea class="form-control" name="secret" rows="7" placeholder="Pesan rahasia"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Enkripsi</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-header">
                <b>Hasil Enkripsi</b>
            </div>
            <div class="card-body">
                <p class="card-text">{{data1}}; {{data2}}</p>
            </div>
        </div>
    </div>
</div>

<script>
    function previewImage() {
    document.getElementById("image-preview").style.display = "block";
    var oFReader = new FileReader();
     oFReader.readAsDataURL(document.getElementById("image-source").files[0]);

    oFReader.onload = function(oFREvent) {
      document.getElementById("image-preview").src = oFREvent.target.result;
    };
  };
</script>
{% endblock content %}

register/templates/lsbextract.html
{% extends 'register.html' %}

{% block meta %}
<title>Enkripsi Vigenere Cipher</title>
{% endblock meta %}

{% block content %}
<h2 align="center">Enkripsi <i>Vigenere Cipher</i></h2><br>
<div class="row justify-content-around">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <b>Proses Ekstrak</b>
            </div>
            <div class="card-body">
                <form method="post" name="enkripsi">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="form-label">Pilih <i>cover image</i> </label>
                        <input class="form-control form-control-sm" name="coverimg" id="image-source" onchange="previewImage();" type="file" accept="image/png">
                        <br><center><img id="image-preview" alt="Image Preview" width="90%"/></center>
                    </div>
                    <div class="mb-3">
                        <textarea class="form-control" name="secret" rows="7" placeholder="Pesan rahasia"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Enkripsi</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-header">
                <b>Hasil Enkripsi</b>
            </div>
            <div class="card-body">
                <p class="card-text">{{data1}}; {{data2}}</p>
            </div>
        </div>
    </div>
</div>

<script>
    function previewImage() {
    document.getElementById("image-preview").style.display = "block";
    var oFReader = new FileReader();
     oFReader.readAsDataURL(document.getElementById("image-source").files[0]);

    oFReader.onload = function(oFREvent) {
      document.getElementById("image-preview").src = oFREvent.target.result;
    };
  };
</script>
{% endblock content %}

register/templates/vcdekripsi.html
{% extends 'register.html' %}

{% block meta %}
<title>Dekripsi Vigenere Cipher</title>
{% endblock meta %}

{% block content %}
<h2 align="center">Dekripsi <i>Vigenere Cipher</i></h2><br>
<div class="row justify-content-around">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <b>Proses </b>
            </div>
            <div class="card-body">
                <form method="post" name="enkripsi">
                    {% csrf_token %}
                    <div class="mb-3">
                        <textarea class="form-control" name="cipherteks" rows="7" placeholder="Cipherteks">{{cipherteks}}</textarea>
                    </div>
                    <div class="mb-3">
                        <textarea class="form-control" name="kunci" rows="7" placeholder="Kunci">{{kunci}}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Dekripsi</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-header">
                <b>Hasil Dekripsi</b>
            </div>
            <div class="card-body">
                <p class="card-text">{{dispcipher}}</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

register/templates/vcenkripsi.html
{% extends 'register.html' %}

{% block meta %}
<title>Enkripsi Vigenere Cipher</title>
{% endblock meta %}

{% block content %}
<h2 align="center">Enkripsi <i>Vigenere Cipher</i></h2><br>
<div class="row justify-content-around">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <b>Proses Enkripsi</b>
            </div>
            <div class="card-body">
                <form method="post" name="enkripsi">
                    {% csrf_token %}
                    <div class="mb-3">
                        <textarea class="form-control" name="plainteks" rows="7" placeholder="Plainteks">{{plainteks}}</textarea>
                    </div>
                    <div class="mb-3">
                        <textarea class="form-control" name="kunci" rows="7" placeholder="Kunci">{{kunci}}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Enkripsi</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-header">
                <b>Hasil Enkripsi</b>
            </div>
            <div class="card-body">
                <p class="card-text">{{dispcipher}}</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="icon" type="image/x-icon" href="{% static 'ico/favico.png' %}">
    {% block meta %}
    {% endblock meta %}

</head>

<body>
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="https://unej.ac.id">
            <img src="http://kemahasiswaan.unej.ac.id/wp-content/uploads/2020/07/cropped-Logo-Baku-UNEJ-2020-Square.png"
                 alt="" width="40" height="40">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:aboutme' %}">Tentang Saya</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Django APP
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'main:data-mhs' %}">Database</a></li>
                        <li><a class="dropdown-item" href="{% url 'register:home' %}">Kriptografi & Steganografi</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Menu Lain</a></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<br><br>
<div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    <br>
    {% block content %}
    {% endblock content %}
    <br>
</div>

<!-- Footer -->
<nav class="navbar fixed-bottom navbar-dark bg-dark" style="height:30px">
    <div class="container-fluid">
            <a class="navbar-brand" style="font-size:11pt; margin-top:-10px;">© Copyright 2021 | Muhammad Seggaf </a>
    </div>
</nav>
<!-- End of Footer -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

templates/register.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="icon" type="image/x-icon" href="{% static 'ico/favico.png' %}">
    {% block meta %}
    {% endblock meta %}
</head>

<body>
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="https://unej.ac.id">
            <img src="http://kemahasiswaan.unej.ac.id/wp-content/uploads/2020/07/cropped-Logo-Baku-UNEJ-2020-Square.png"
                 alt="" width="40" height="40">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:aboutme' %}">Tentang Saya</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Django APP
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'main:data-mhs' %}">Database</a></li>
                        <li><a class="dropdown-item" href="{% url 'register:home' %}">Kriptografi & Steganografi</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Menu Lain</a></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<br><br><br>
<div class="container">
    {% block content %}
    {% endblock content %}
</div>
<br><br>

<!-- Footer -->
<nav class="navbar fixed-bottom navbar-dark bg-dark" style="height:30px">
    <div class="container-fluid">
            <a class="navbar-brand" style="font-size:11pt; margin-top:-10px;">© Copyright 2021 | Muhammad Seggaf </a>
    </div>
</nav>
<!-- End of Footer -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

</body>
</html>